vinyl_shop/products/urls.py
from django.urls import path

from products.views import products

app_name = 'products'

urlpatterns = [
    path('', products, name='index')
]

vinyl_shop/vinyl_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('products/', include('products.urls', namespace='products'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vinyl_shop/orders/models.py
from django.db import models

# Create your models here.

vinyl_shop/products/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='artist_image', null=True, blank=True)

    def __str__(self):
        return self.name


class Label(models.Model):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='artist_image', null=True, blank=True)

    def __str__(self):
        return self.name
    

class Album(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    year_release = models.DateField()
    image = models.ImageField(upload_to='album_image', null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    label = models.ForeignKey(to=Label, on_delete=models.CASCADE)
    artist = models.ManyToManyField(to=Artist)
    genre = models.ManyToManyField(to=Genre)

    def __str__(self):
        genres_names = ", ".join([genre.name for genre in self.genres.all()])
        return f"{self.title} - {genres_names} by {self.artist.name}"
    

class Track(models.Model):
    title = models.CharField(max_length=256)
    duration = models.TimeField()
    album = models.ForeignKey(to=Album, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} - {self.album.title}"

vinyl_shop/users/models.py
from django.db import models

# Create your models here.

vinyl_shop/orders/views.py
from django.shortcuts import render

# Create your views here.

vinyl_shop/products/views.py
from django.shortcuts import render

from products.models import Album, Genre, Artist


def index(request):
    context = {
        'title': 'Home'
    }
    return render(request, 'products/index.html', context)

def about(request):
    context = {
        'title': 'About'
    }
    return render(request, 'products/about.html', context)

def products(request):
    context = {
        'title': 'Vinyl',
        'albums': Album.objects.all(),
        'genres': Genre.objects.all(),
        'artists': Artist.objects.all()
    }
    return render(request, 'products/products.html', context)

vinyl_shop/users/views.py
from django.shortcuts import render

# Create your views here.

vinyl_shop/products/templates/products/about.html
{% extends 'products/base.html' %}
{% load static %}

{% block main %}
    
{% endblock %}

vinyl_shop/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <title>{{ title }}</title>
</head>
<body>
    <header class="container">
        <a href="{% url 'index' %}" class="header-logo">
            <img src="{% static 'img/logo-icon.svg' %}" 
                 alt="logo" loading="lazy"
                 width="40px" height="40px">
        </a>
        <nav class="header-nav">
            <ul class="header-menu-list">
                <li class="header-menu-item"><a href="{% url 'index' %}" class="header-menu-link">Home</a></li>
                <li class="header-menu-item"><a href="{% url 'products:index' %}" class="header-menu-link">Vinyl</a></li>
                <li class="header-menu-item"><a href="#" class="header-menu-link">Blog</a></li>
                <li class="header-menu-item"><a href="{% url 'about' %}" class="header-menu-link">About</a></li>
            </ul>
        </nav>
        <div class="header-actions">
            <ul class="header-actions-list">
                <li class="header-actions-item"><a href="#" class="header-actions-link">Sign In</a></li>
                <li class="header-actions-item"><a href="#" class="header-actions-link">Profile</a></li>
            </ul>
        </div>
    </header>
    <main>
        {% block main %} {% endblock %}
    </main>
</body>
</html>

vinyl_shop/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block main %}
    
{% endblock %}

vinyl_shop/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block main %}
        <section class="container products">
            <h1 class="products-list-title">Vinyl</h1>
            <ul class="products-list">
                <li class="products-list-item">
                    <a href="#" class="products-list-link">
                        <div class="album-img">
                            <img src="{{ album.image.url }}" alt="album">
                        </div>
                        <div class="product-info">
                            <h2 class="artist-name">{{ album.artist.name }}</h2>
                            <h3 class="album-name">{{ album.title }}</h3>
                            <p class="price">{{ album.price }} USD</p>
                        </div>
                    </a>
                </li>
                {% for album in albums %}
                <li class="products-list-item">
                    <a href="#" class="products-list-link">
                        <div class="album-img">
                            <img src="{{ album.image.url }}" alt="album">
                        </div>
                        <div class="product-info">
                            <h2 class="artist-name">{{ album.artist.name }}</h2>
                            <h3 class="album-name">{{ album.title }}</h3>
                            <p class="price">{{ album.price }} USD</p>
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
{% endblock %}